name: triage

on:
  issues:
    types: [opened, edited, reopened]
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  issue-labeler:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Run issue labeler
        uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          include-body: 1
          sync-labels: 1

  pr-labeler:
    if: github.event_name == 'pull_request_target' && github.event.action != 'edited'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run PR labeler
        uses: actions/labeler@v6
        with:
          configuration-path: .github/pr-labeler.yml
          sync-labels: false

  request-info:
    if: github.event.action == 'opened' || github.event.action == 'edited'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Run request info
        uses: tomdewildt/request-info@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  first-interaction:
    if: github.event.action == 'opened' && github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Run first interaction
        uses: tomdewildt/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
